<main class="container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center flex-column">
            <h4 align="center">EDITAR ITEM</h4>
            <form action="/save_item" method="post">
                <div class="form-group">
                    <input type="text" placeholder="Nome do Item" class="form-control" name="name" required>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Descrição do Item" class="form-control" name="description" required>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Dano do Item" class="form-control" name="damage">
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Efeito" class="form-control" name="efect" required>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="CA" class="form-control" name="ca">
                </div>

                <div class="form-group d-none">
                    <input type="number" name="id_character" value="<?= $_GET['id'] ?>">
                </div>

                <div class="col-12 d-flex justify-content-center">
                    <button type="submit">CRIAR</button>
                </div>
            </form>

        </div>
    </div>
</main>