<?php
    include 'function.php';
?>
<main class="container">
<form action="/edit_character" method="post" enctype="multipart/form-data">
    <div class="row" style="float: right;">
        <img src="img/img_character/<?= $this->view->character->imagem ?>" alt="imagem personagem" class="img-fluid img-thumbnail" style="max-width: 180px;">
    </div>

    <div>
        <a id="btnEditar" class="btn btn-warning">Editar</a>
        <a href="/create_habilities?id=<?= $_GET['id'] ?>" class="btn btn-primary">Criar Habilidade</a>
        <a href="/delete_character?id=<?= $_GET['id'] ?>" class="btn btn-danger">Excluir Personagem</a>
    </div>

    <div class="row" id="geral">
        <h4 align="center">GERAL</h4>
        <div class="col-12" id="geralContent">
        <div class="d-flex justify-content-center">
            <div class="form-group">
                <input type="text" name="name" required id="" value="<?= $this->view->character->nome ?>" class="form-control">
            </div>
            <div class="form-group">
                <input type="text" name="class" required  class="form-control" value="<?= $this->view->character->classe ?>">
            </div>
            <div class="form-group">
                <input type="number" name="age" required  class="form-control" value="<?= $this->view->character->idade ?>">
            </div>
        </div>
            
        </div>
    </div>
    <div class="row" id="especificacoes">
        <h4 align="center">ESPECIFICAÇOES</h4>
        <div class="col-12" id="especificacoesContent">
            <div class="d-flex justify-content-center">
                <div class="form-group">
                    <input type="number" name="life" required id=""  value="<?= $this->view->character->vida ?>" class="form-control">
                </div>
                <div class="form-group">
                    <input type="number" name="energy" required  class="form-control" value="<?= $this->view->character->energia ?>">
                </div>
                <div class="form-group">
                    <input type="number" name="armor_class" required  class="form-control" value="<?= $this->view->character->ca ?>">
                </div>
            </div> 
        </div>
    </div>
    <div class="row" id="caracteristicas">
        <h4 align="center">CARACTERISTICAS</h4>
        <div class="col-12" id="caracteristicasContent">
            <div class="d-flex justify-content-center">
                <div class="form-group">
                    <input type="text" name="height" id="" required  value="<?= $this->view->character->altura ?>" class="form-control">
                </div>
                <div class="form-group">
                    <input type="text" name="color_hear" required  class="form-control" value="<?= $this->view->character->cabelo ?>">
                </div>
                <div class="form-group">
                    <input type="text" name="personality" required  class="form-control" value="<?= $this->view->character->personalidade ?>">
                </div>
                <div class="form-group">
                    <input type="text" name="details" required  class="form-control" value="<?= $this->view->character->detalhes ?>">
                </div>
            </div>
            
        </div>
    </div>
        <div class="row">
            <div class="col-5 col-md-5 d-flex justify-content-center">
                <div class="form-group">
                    <h4>Nome dos Atributos</h4>
                    <input type="text"  name="name_attribute_1" id="" class="form-control" value="<?= $this->view->character->nome_atributo_1 ?>" required>
                    <input type="text"  name="name_attribute_2" id="" class="form-control" value="<?= $this->view->character->nome_atributo_2 ?>" required>
                    <input type="text"  name="name_attribute_3" id="" class="form-control" value="<?= $this->view->character->nome_atributo_3 ?>" required>
                    <input type="text"  name="name_attribute_4" id="" class="form-control" value="<?= $this->view->character->nome_atributo_4 ?>" required>
                    <input type="text"  name="name_attribute_5" id="" class="form-control" value="<?= $this->view->character->nome_atributo_5 ?>" required>
                    <input type="text"  name="name_attribute_6" id="" class="form-control" value="<?= $this->view->character->nome_atributo_6 ?>" required>
                </div>
            </div>
            <div class="col-2 col-md-2 d-block">
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
            </div>
            <div class="col-5 col-md-5 d-flex justify-content-center">
                <div class="form-group">
                    <h4>Valor dos Atributos</h4>
                    <input type="number"  name="value_attribute_1" id="" class="form-control" value="<?= $this->view->character->valor_atributo_1?>" required> 
                    <input type="number"  name="value_attribute_2" id="" class="form-control" value="<?= $this->view->character->valor_atributo_2 ?>" required>
                    <input type="number"  name="value_attribute_3" id="" class="form-control" value="<?= $this->view->character->valor_atributo_3 ?>" required>
                    <input type="number"  name="value_attribute_4" id="" class="form-control" value="<?= $this->view->character->valor_atributo_4 ?>" required>
                    <input type="number"  name="value_attribute_5" id="" class="form-control" value="<?= $this->view->character->valor_atributo_5 ?>" required>
                    <input type="number"  name="value_attribute_6" id="" class="form-control" value="<?= $this->view->character->valor_atributo_6 ?>" required>
                </div>
            </div>
        </div>
        <div class="row">
            <h4 align="center">RECURSOS</h4>
            <div class="col-5 col-md-5 d-flex justify-content-center">
                <div class="form-group">
                    <h4>Nome dos Recursos</h4>
                    <input type="text"  name="resource_1" id="" class="form-control" value="<?= $this->view->character->nome_recurso_1 ?>" required>
                    <input type="text"  name="resource_2" id="" class="form-control" value="<?= $this->view->character->nome_recurso_2 ?>" required>
                    <input type="text"  name="resource_3" id="" class="form-control" value="<?= $this->view->character->nome_recurso_3 ?>" required>
                    <input type="text"  name="resource_4" id="" class="form-control" value="<?= $this->view->character->nome_recurso_4 ?>" required>
                </div>
            </div>

            <div class="col-2 col-md-2 d-block">
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
                <div>
                    <img src="img/equality.jpg" alt="recebe" class="img-fluid img-equality">
                </div>
            </div>

            <div class="col-5 col-md-5 d-flex justify-content-center">
                <div class="form-group">
                    <h4>Valor dos Recursos</h4>
                    <input type="number" value="<?= $_GET['id'] ?>" class="d-none" name="id">
                    <input type="number"  name="value_resource_1" id="" class="form-control" value="<?= $this->view->character->valor_recurso_1 ?>" required>
                    <input type="number"  name="value_resource_2" id="" class="form-control" value="<?= $this->view->character->valor_recurso_2 ?>" required> 
                    <input type="number"  name="value_resource_3" id="" class="form-control" value="<?= $this->view->character->valor_recurso_3 ?>" required>
                    <input type="number"  name="value_resource_4" id="" class="form-control" value="<?= $this->view->character->valor_recurso_4 ?>" required>
                </div>
            </div>
        </div>
        <div class="row">
            <h4 align="center">HISTORIA</h4>
            <div class="col-12 d-flex justify-content-center">
                <div class="form-group">
                    <textarea name="history" id="" cols="93" rows="10" required><?= $this->view->character->historia ?></textarea>
                </div>
            </div>

            <div style="display: none;" id="input-img">
                <div class="col-12 d-flex justify-content-center">
                    <div class="form-group">
                        <input type="file" class="form-control" name="image">
                    </div>
                </div>
            </div>
        </div>
        <div id="btn-form" class="col-12" style="display: none;">
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn-make-character">EDITAR FICHA</button>
            </div>
            

        </div>

        <div class="row d-flex justify-content-center">
            <h4 align="center">HABILIDADES</h4>
            <?php if (empty($this->view->habilities)) {

            }else { ?>
                <?php foreach ($this->view->habilities as $habilitie) { ?>
                    <div class="col-4 d-flex  flex-column habilitie">
                        <div class="d-flex justify-content-end align-items-start">
                            <div><a href="delete_habilitie?id=<?= $habilitie->id ?>&id_personagem=<?= $_GET['id'] ?>" class="btn btn-outline-danger"><i class="fas fa-minus-circle"></i></a></div>
                            <div><a href="edit_habilitie?id=<?= $habilitie->id ?>&id_personagem=<?= $_GET['id'] ?>" class="btn btn-outline-warning"><i class="fas fa-pencil-alt"></i></a></div>
                        </div>
                        
                    
                            <h5 align="center"><?= $habilitie->nome ?></h5>
                            <div class="description-hab">
                                <p><?= $habilitie->descricao ?></p>
                            </div>
                            <p><span>Efeito:</span> <?= $habilitie->efeito ?></p>
                            <p><span>Dano:</span> <?= $habilitie->dano ?></p>
                            <p><span>Custo:</span> <?= $habilitie->custo ?> de energia</p>
                            <p><span>Cooldown:</span> <?= $habilitie->cooldown ?> turnos</p>
                    </div> <?php } } ?>
        </div>
</form>
</main>

<script>
    $(document).ready( () => {
        $('input').attr('readonly', 'readonly');

        $('#btnEditar').on('click', () => {
            $('input').removeAttr('readonly');

            $('#btn-form').show();
            $('#input-img').show();
        });

    });
</script>
