<main class="container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center flex-column">
            <h4 align="center">EDITAR ITEM</h4>
            <form action="/update_item?id=<?= $_GET['id'] ?>&id_personagem=<?= $_GET['id_personagem'] ?>" method="post">
                <div class="form-group">
                    <input type="text" placeholder="Nome do Item" class="form-control" value="<?= $this->view->item->nome ?>" name="name" required>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Descrição do Item" class="form-control" value="<?= $this->view->item->descricao ?>"  name="description" required>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Dano do Item" class="form-control" value="<?= $this->view->item->dano ?>"  name="damage">
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Efeito" class="form-control" name="efect" value="<?= $this->view->item->efeito ?>"  required>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="CA" class="form-control" value="<?= $this->view->item->ca ?>"  name="ca">
                </div>

                <div class="form-group d-none">
                    <input type="number" name="id_character" value="<?= $_GET['id'] ?>">
                </div>

                <div class="col-12 d-flex justify-content-center">
                    <button type="submit">CRIAR</button>
                </div>
            </form>

        </div>
    </div>
</main>