<main class="container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center flex-column">
            <h4 align="center">CRIAR HABILIDADE</h4>
            <form action="/update_habilities?id=<?= $_GET['id'] ?>&id_personagem=<?= $_GET['id_personagem'] ?>" method="post">
                <div class="form-group">
                    <input type="text" placeholder="Nome da Habilidade" class="form-control" name="name" value="<?= $this->view->habilitie->nome ?>" required>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Descrição da Habilidade" class="form-control" name="description" value="<?= $this->view->habilitie->descricao ?>" required>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Efeito da Habilidade" class="form-control" name="efect" value="<?= $this->view->habilitie->efeito ?>">
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Dano da Habilidade" class="form-control" name="damage" value="<?= $this->view->habilitie->dano ?>">
                </div>
                <div class="form-group">
                    <input type="number" placeholder="Custo da Habilidade" class="form-control" name="cost" value="<?= $this->view->habilitie->custo ?>">
                </div>
                <div class="form-group">
                    <input type="number" placeholder="Cooldown" class="form-control" name="cooldown" value="<?= $this->view->habilitie->cooldown ?>">
                </div>

               
                <div class="col-12 d-flex justify-content-center">
                    <button type="submit">EDITAR</button>
                </div>
            </form>

        </div>
    </div>
</main>