<main id="banner">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-12 col-sm-12 skendRPG d-flex justify-content-center align-items-center">
                <span class="skend">skend</span><span class="rpg">RPG</span>
            </div>
        </div>

        <div class="row d-flex justify-content-between">
            <div class="col-12 col-md-5 mt-3 card">
                <div class="card-body d-flex flex-column justify-content-center align-items-center">
                    <h4>CRIE PERSONAGENS</h4>
                    <p>
                        Aenean lacinia dui ut orci tempus, dignissim commodo tortor ullamcorper. Donec ex lacus, auctor non lectus suscipit, consequat convallis sem.   Quisque at erat fermentum, laoreet magna vitae, vehicula sapien. Nulla mattis nec velit dapibus porttitor. Sed pharetra, mi id iaculis feugiat, sapien ligula lacinia elit, sit amet suscipit magna nisi venenatis sem.
                    </p>
                </div>
                
            </div>
            <div class="col-12 col-md-5 mt-3 card">
                <div class="card-body d-flex flex-column justify-content-center align-items-center">
                    <h4>FICHA EM TEMPO REAL</h4>
                    <p>
                        Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis convallis suscipit libero ac consectetur. Mauris nisl tortor, tempus a tellus id, viverra tincidunt nunc. Suspendisse porta lorem lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam neque libero, gravida placerat convallis sit amet, lacinia eu tortor.
                    </p>
                </div>
                
            </div>
        </div>
    </div>
</main>





