<body id="login">
    <main class="container d-flex aligns-items-center justify-content-center mt-5">
        <div class="row mt-5">
            <div class="col-12 mt-3">
                <div id="img-login" class="d-flex justify-content-center aligns-items-center">
                    <img src="img/anonymus.png" alt="" class="img-fluid" style="max-width: 140px;">
                </div>
                
                <form action="/user_login" method="post" class="mt-3">
                    <div class="form-group">
                        <input type="email" required name="email" class="form-control" placeholder="E-mail"
                        >
                    </div>

                    <div class="form-group">
                        <input type="password" name="password" required min="6" class="form-control" placeholder="Senha">
                    </div>

                    <div class="form-group d-flex justify-content-center">
                        <button>Entrar</button>
                    </div>
                    
                </form>
            </div>
        </div>
    </main>
</body>

