<main class="container">
    <div class="row">
        <div class="col-12 col-md-6 division">
        <div class="d-flex justify-content-center add_character mt-5">
                <a href="/make_character"><img src="img/sum.png" alt="imagem de soma para adicionar personagem" class="img-fluid" style="max-width: 120px;"></a>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <h3>Listagem de Personagens</h3>
            <?php foreach($this->view->character as $character)  {?>
                <div id="list-character" class="d-flex justify-column">
                    <a href="/character?id=<?= $character->id ?>"><?= $character->nome ?></a>
                </div>
            <?php } ?>

        </div>
    </div>
</main>