<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 division">
        <div class="d-flex justify-content-center add_character mt-5">
                <a href="/make_character"><img src="img/sum.png" alt="imagem de soma para adicionar personagem" class="img-fluid" style="max-width: 120px;"></a>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <h3>Listagem de Personagens</h3>
            <p>personagem xx</p>
            <p>personagem xx</p>
            <p>personagem xx</p>
            <p>personagem xx</p>
            <p>personagem xx</p>
            <p>personagem xx</p>

        </div>
    </div>
</div>