<body id="login">
        
    <main class="container">
        <form enctype="multipart/form-data" action="user_edit" method="post">
            <div class="row mt-5 d-flex aligms-items-center p-5">
                <div class="col-12 col-md-6 mt-5">
                    <div class="form-group mb-3">
                        <input type="text" class="form-control" value="<?= $this->view->user->nome ?>" required id="name" name="name" aria-describedby="nameHelp">
                    </div>
                    <div class="form-group mb-3">
                        <input type="email" class="form-control" value="<?= $this->view->user->email ?>" required id="email" name="email" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group mb-3">
                        <input type="password" class="form-control" placeholder="Informe sua senha atual ou nova senha" required min="8" name="password" id="password">
                    </div>
                </div>
                <div class="col-12 col-md-6 mt-5" style="position: relative; top: -48px;">
                    <div class="d-flex justify-content-center p-1">
                        <img src="img/<?= $this->view->user->imagem ?>" alt="imagem do perfil" class="img-fluid" style="max-width: 150px;">
                    </div>
                    <div class="form-group mb-3">
                        <input type="file" name="image" id="image" class="form-control">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 d-flex justify-content-center">
                    <button>Alterar</button>
                </div>
        </form>
    </main>
</body>

