<html lang="pt-br">
	<head>
		<meta charset="utf-8" />
		<title>SkendRPG</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="js/jquery.js"></script>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/style.css">

	</head>

	<body>

		<header class="container">
			<div class="container">
				<nav class="d-flex justify-content-between">
					<div class="d-inline-block">
						<img src="img/img_profile/<?= $this->view->user->imagem ?>" alt="imagem do perfil" class="img-fluid img-thumbnail" style="max-width: 120px;">
						<div class="info">
							<span class="d-block">ID: #<?= $this->view->user->id ?></span>
							<span class="">Personagens: 2</span>
						</div>
						
					</div>
					<div class="d-flex align-items-center">
						<a href="/app" class="btn-menu-app">INICIO</a>
					</div>
					<div class="dropdown d-flex lign-items-center">
						<a class="btn" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
							<img src="img/gear.png" alt="" class="img-fluid" style="max-width: 60px;">
						</a>

						<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
							<li><a class="dropdown-item" href="/profile">Perfil</a></li>
							<li><a class="dropdown-item" href="/logoff">Sair</a></li>
						</ul>
					</div>
				</nav>
			</div>
		</header>

		<hr>

		<?= $this->content() ?>
	</body>

</html>
